config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :orders do
      resources :invoices, only: [:index, :new, :create]
      resources :documents, only: [:index, :new, :create]
    end
    resources :shipments do
      resource :shipment_documents, only: [:show]
    end
    resources :invoices, except: [:index, :new, :create]
    resources :documents, except: [:index, :new, :create]
  end
end

app/models/spree/document.rb
module Spree
  class Document < ActiveRecord::Base
    has_attached_file :document,
      url: Spree::Config.attachment_default_url.gsub('/products/', '/documents/'),
      path: Spree::Config.attachment_path.gsub('/products/', '/documents/')

    include Spree::Core::S3Support
    supports_s3 :document

    belongs_to :source, polymorphic: true

    validate :name, presence: true

    def upload_content?
      upload_content_type.to_s.match(/\/(pdf|doc|docx|xls|xlsx|odt|ods)/)
    end
  end
end

app/controllers/spree/admin/documents_controller.rb
module Spree
  module Admin
    class DocumentsController < Spree::Admin::ResourceController
      belongs_to 'spree/order', find_by: :number

      private

      def location_after_save
        polymorphic_path([:admin, @document.source, :documents])
      end

      def collection_url
        if @document.source.present?
          polymorphic_path([:admin, @document.source, :documents])
        else
          super
        end
      end

      def find_resource
        if parent && parent.respond_to?(controller_name)
          parent.send(controller_name).find(params[:id])
        else
          model_class.find(params[:id])
        end
      end
    end
  end
end

app/views/spree/admin/documents/_form.html.erb
<div>
  <div class="alpha twelve columns">
    <fieldset class="no-border-bottom">
      <legend align="center"><%= Spree.t(:document, scope: :invoices_and_documents) %></legend>
      <div class="alpha six columns">
        <div class="field">
          <%= f.label :name, Spree.t(:document_name, scope: :invoices_and_documents) %>
          <%= f.text_field :name, class: 'fullwidth' %>
        </div>
        <div class="field">
          <%= f.label :description, Spree.t(:document_description, scope: :invoices_and_documents) %>
          <%= f.text_area :description, class: 'fullwidth', rows: 8 %>
        </div>
      </div>
      <div class="omega six columns">
        <div class="field">
          <%= f.label :document, Spree.t(:document_file, scope: :invoices_and_documents) %>
          <%= f.file_field :document, class: 'fullwidth' %>
        </div>
      </div>
    </fieldset>
  </div>
  <div class="clear"></div>
</div>

app/views/spree/admin/documents/_order_tab.html.erb
<% if can?(:read, Spree::Document) %>
  <li<%== ' class="active"' if current == 'Documents' %>>
    <%= link_to_with_icon('icon-file', Spree.t(:documents, scope: :invoices_and_documents), spree.admin_order_documents_path(@order)) %>
  </li>
<% end %>

app/views/spree/admin/documents/edit.html.erb
<% @order = @document.source %>

<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Documents' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:edit_document, scope: :invoices_and_documents) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back), collection_url, icon: 'icon-arrow-left' %>
  </li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @document } %>

<%= form_for [:admin, @document] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <div class="clear"></div>

    <%= render partial: 'spree/admin/shared/edit_resource_links' %>

  </fieldset>
<% end %>

app/views/spree/admin/documents/index.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Documents' } %>

<%= csrf_meta_tags %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:documents, scope: :invoices_and_documents) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Document) %>
    <li><%= button_link_to Spree.t(:new_document, scope: :invoices_and_documents), new_admin_order_document_path(@order), icon: 'icon-plus' %></li>
  <% end %>
  <% if can?(:admin, Spree::Order) %>
    <li><%= button_link_to Spree.t(:back_to_order_details, scope: :invoices_and_documents), edit_admin_order_path(@order), icon: 'icon-arrow-left' %></li>
  <% end %>
<% end %>

<% unless @documents.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_results, scope: :invoices_and_documents) %>
  </div>
<% else %>
  <table class="index">
    <colgroup>
      <col style="width: 20%">
      <col style="width: 35%">
      <col style="width: 20%">
      <col style="width: 10%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr>
        <th><%= Spree.t(:document_name, scope: :invoices_and_documents) %></th>
        <th><%= Spree.t(:document_description, scope: :invoices_and_documents) %></th>
        <th><%= Spree.t(:document_file, scope: :invoices_and_documents) %></th>
        <th><%= Spree.t(:document_file_size, scope: :invoices_and_documents) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @documents.each do |document|%>
        <tr id="<%= spree_dom_id document %>" class="<%= cycle('odd', 'even')%>">
          <td><%= document.name %></td>
          <td><%= simple_format(document.description) %></td>
          <td><%= link_to document.document_file_name, document.document.url, target: '_blank' %></td>
          <td><%= number_to_human_size(document.document_file_size) %></td>
          <td class="actions">
            <%= link_to_with_icon 'icon-pencil', Spree.t(:edit), spree.edit_admin_document_path(document), no_text: true %>
            <%= link_to_with_icon 'icon-trash', Spree.t(:edit), spree.admin_document_path(document), no_text: true, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/documents/new.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Documents' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:new_document, scope: :invoices_and_documents) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back), collection_url, icon: 'icon-arrow-left' %>
  </li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @document } %>

<%= form_for [:admin, @order, @document], multipart: true do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <div class="clear"></div>

    <%= render partial: 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>