config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :orders do
      resources :invoices, only: [:index, :new, :create]
      resources :documents, only: [:index, :new, :create]
    end
    resources :shipments do
      resource :shipment_documents, only: [:show]
    end
    resources :invoices, except: [:index, :new, :create]
    resources :documents, except: [:index, :new, :create]
  end
end

app/models/spree/invoice.rb
module Spree
  class Invoice < ActiveRecord::Base
    belongs_to :order
    belongs_to :invoice_address
    has_many :invoice_lines, dependent: :destroy

    default_scope -> { order(:invoice_number) }
    scope :debit, -> { where(is_credit: false) }
    scope :credit, -> { where(is_credit: true) }

    validate :order_id, :invoice_address_id, presence: true
    validate :invoice_number, :invoice_date, presence: true
    validate :invoice_number, uniqueness: true
    validate :tax_rate, nummericality: { greater_than_or_equal_to: 0, less_then_or_equal_to: 1 }
    validate :tax_total, :item_total, :invoice_total, nummericality: true

    accepts_nested_attributes_for :invoice_address, :invoice_lines, :reject_if => :all_blank, :allow_destroy => true

    set_callback :initialize, :after, :set_invoice_number
    set_callback :initialize, :after, :set_invoice_date
    set_callback :initialize, :after, :set_order_reference
    set_callback :initialize, :after, :set_invoice_address
    set_callback :initialize, :after, :set_tax_rate
    set_callback :validation, :before, :set_invoice_number
    set_callback :save, :after, :send_invoice_to_customer, :set_credit_debit, :set_invoice_total, :set_tax_total, :set_item_total
    set_callback :destroy, :after, :delete_invoice_address

    def self.next_invoice_number
      (Spree::Invoice.order(:invoice_number).where('invoice_number IS NOT NULL AND invoice_number != 0').last.try(:invoice_number) || Spree::Config[:invoice_number_start] || 0) + 1
    end

    def invoice_recipient
      return unless invoice_address.present?
      return [invoice_address.first_name, invoice_address.last_name].compact.join(' ') if invoice_address.has_name?
      invoice_address.company if invoice_address.has_company?
    end

    def currency
      if order && order.currency?
        order.currency
      else
        Spree::Config[:currency]
      end
    end

    def display_item_total
      Spree::Money.new(item_total, { currency: currency })
    end

    def display_tax_total
      Spree::Money.new(tax_total, { currency: currency })
    end

    def display_invoice_total
      Spree::Money.new(invoice_total, { currency: currency })
    end

    private

    def delete_invoice_address
      invoice_address.destroy!
    end

    def set_invoice_date
      return if invoice_date.present?
      self.invoice_date = Date.today
    end

    def set_invoice_number
      return if invoice_number.present?
      self.invoice_number = Invoice.next_invoice_number
    end

    def set_tax_rate
      return if tax_rate.present?
      self.tax_rate = order.tax_zone.tax_rates.first.try(:amount) || 0
    end

    def set_order_reference
      return if order_reference.present? || !order
      self.order_reference = "#{order.number}-#{(order.invoices.count + 1)}"
    end

    def set_invoice_address
      return if invoice_address.present?
      self.invoice_address = build_invoice_address(order: order)
    end

    def set_item_total
      item_total = 0

      invoice_lines.each do |line|
        item_total += line.unit_price * line.units
      end

      self.update_column(:item_total, item_total)
    end

    def set_tax_total
      tax_total = 0

      invoice_lines.each do |line|
        next if !line.taxable? || line.tax_included?
        item_total = line.unit_price * line.units
        tax_total += item_total * self.tax_rate
      end

      self.update_column(:tax_total, tax_total)
    end

    def set_invoice_total
      self.update_column(:invoice_total, self.tax_total + self.item_total)
    end

    def set_credit_debit
      self.update_column(:is_credit, invoice_total < 0)
    end

    def send_invoice_to_customer
      return unless order.present? && order.user.present? && order.ship_address.present?

      message = Spree::InvoiceMailer.notify(self)
      message.deliver unless message.nil?
    end
  end
end

app/controllers/spree/admin/invoices_controller.rb
module Spree
  module Admin
    class InvoicesController < Spree::Admin::ResourceController
      prawnto prawn: { page_size: 'A4', margin: 20 }

      belongs_to 'spree/order', find_by: :number

      def show
        respond_to do |format|
          format.html
          format.pdf
        end
      end

      private

      def location_after_save
        admin_order_invoices_path(@invoice.order)
      end

      def collection_url
        if @invoice.order.present?
          admin_order_invoices_path(@invoice.order)
        else
          super
        end
      end

      def find_resource
        if parent && parent.respond_to?(controller_name)
          parent.send(controller_name).find(params[:id])
        else
          model_class.find(params[:id])
        end
      end
    end
  end
end

app/views/spree/admin/invoices/_form.html.erb
<div>
  <div class="alpha twelve columns">
    <fieldset class="no-border-bottom">
      <legend align="center"><%= Spree.t(:invoice, scope: :invoices_and_documents) %></legend>
      <div class="alpha six columns">
        <div class="field">
          <%= f.label :invoice_number, Spree.t(:invoice_number, scope: :invoices_and_documents) %>
          <%= f.text_field :invoice_number, class: 'fullwidth', disabled: true %>
        </div>
        <div class="field">
          <%= f.label :order_reference, Spree.t(:order_reference, scope: :invoices_and_documents) %>
          <%= f.text_field :order_reference, class: 'fullwidth' %>
        </div>
      </div>
      <div class="omega six columns">
        <div class="field">
          <%= f.label :invoice_date, Spree.t(:invoice_date, scope: :invoices_and_documents) %>
          <%= f.text_field :invoice_date, class: 'fullwidth datepicker', value: datepicker_field_value(@invoice.invoice_date) %>
        </div>
        <div class="field">
          <%= f.label :tax_rate, Spree.t(:tax_rate, scope: :invoices_and_documents) %>
          <%= f.text_field :tax_rate, class: 'fullwidth' %>
        </div>
      </div>
    </fieldset>
  </div>
  <div class="clear"></div>
</div>

app/views/spree/admin/invoices/_order_tab.html.erb
<% if can?(:read, Spree::Invoice) %>
  <li<%== ' class="active"' if current == 'Invoices' %>>
    <%= link_to_with_icon('icon-money', Spree.t(:invoices, scope: :invoices_and_documents), spree.admin_order_invoices_path(@order)) %>
  </li>
<% end %>

app/views/spree/admin/invoices/edit.html.erb
<% @order = @invoice.order %>

<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Invoices' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:edit_invoice, scope: :invoices_and_documents) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back), collection_url, icon: 'icon-arrow-left' %>
  </li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @invoice } %>

<%= form_for [:admin, @invoice] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <%= f.fields_for :invoice_address do |invoice_address_fields| %>
      <%= render partial: 'spree/admin/invoice_addresses/form', locals: { f: invoice_address_fields } %>
    <% end %>

    <div>
      <div class="alpha twelve columns">
        <fieldset class="no-border-bottom">
          <legend align="center"><%= Spree.t(:invoice_lines, scope: :invoices_and_documents) %></legend>
          <div class="nested-form-wrapper">
            <%= f.fields_for :invoice_lines do |invoice_line_fields| %>
              <%= render partial: 'spree/admin/invoice_lines/fields', locals: { f: invoice_line_fields } %>
            <% end %>
          </div>
          <%= link_to_add_association Spree.t(:add_invoice_line, scope: :invoices_and_documents), f, :invoice_lines, data: { :'association-insertion-node' => 'div.nested-form-wrapper', :'association-insertion-method' => 'append' }, partial: 'spree/admin/invoice_lines/fields', class: 'button icon-plus' %>
        </fieldset>
        <div class="clear"></div>
      </div>
    </div>

    <div class="clear"></div>

    <%= render partial: 'spree/admin/shared/edit_resource_links' %>

  </fieldset>
<% end %>

app/views/spree/admin/invoices/index.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Invoices' } %>

<%= csrf_meta_tags %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:invoices, scope: :invoices_and_documents) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Invoice) %>
    <li><%= button_link_to Spree.t(:new_invoice, scope: :invoices_and_documents), new_admin_order_invoice_path(@order), icon: 'icon-plus' %></li>
  <% end %>
  <% if can?(:admin, Spree::Order) %>
    <li><%= button_link_to Spree.t(:back_to_order_details, scope: :invoices_and_documents), edit_admin_order_path(@order), icon: 'icon-arrow-left' %></li>
  <% end %>
<% end %>

<% unless @invoices.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_results, scope: :invoices_and_documents) %>
  </div>
<% else %>
  <table class="index">
    <colgroup>
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr>
        <th><%= Spree.t(:invoice_number, scope: :invoices_and_documents) %></th>
        <th><%= Spree.t(:invoice_date, scope: :invoices_and_documents) %></th>
        <th><%= Spree.t(:invoice_total, scope: :invoices_and_documents) %></th>
        <th><%= Spree.t(:invoice_recipient, scope: :invoices_and_documents) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @invoices.each do |invoice|%>
        <tr id="<%= spree_dom_id invoice %>" class="<%= cycle('odd', 'even')%>">
          <td><%= invoice.invoice_number %></td>
          <td><%= invoice.invoice_date %></td>
          <td><%= number_to_currency(invoice.invoice_total, unit: '€', separator: ',', delimiter: '.') %></td>
          <td><%= invoice.invoice_recipient %></td>
          <td class="actions">
            <%= link_to_with_icon 'icon-print', Spree.t(:download_pdf, scope: :invoices_and_documents), spree.admin_invoice_path(invoice, format: :pdf), no_text: true, target: '_blank' %>
            <%= link_to_with_icon 'icon-pencil', Spree.t(:edit), spree.edit_admin_invoice_path(invoice), no_text: true %>
            <%= link_to_with_icon 'icon-trash', Spree.t(:edit), spree.admin_invoice_path(invoice), no_text: true, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/invoices/new.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Invoices' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:new_invoice, scope: :invoices_and_documents) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back), collection_url, icon: 'icon-arrow-left' %>
  </li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @invoice } %>

<%= form_for [:admin, @order, @invoice] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <%= f.fields_for :invoice_address do |invoice_address_fields| %>
      <%= render partial: 'spree/admin/invoice_addresses/form', locals: { f: invoice_address_fields } %>
    <% end %>

    <div>
      <div class="alpha twelve columns">
        <fieldset class="no-border-bottom">
          <legend align="center"><%= Spree.t(:invoice_lines, scope: :invoices_and_documents) %></legend>
          <div class="nested-form-wrapper">
            <%= f.fields_for :invoice_lines do |invoice_line_fields| %>
              <%= render partial: 'spree/admin/invoice_lines/fields', locals: { f: invoice_line_fields } %>
            <% end %>
          </div>
          <%= link_to_add_association Spree.t(:add_invoice_line, scope: :invoices_and_documents), f, :invoice_lines, data: { :'association-insertion-node' => 'div.nested-form-wrapper', :'association-insertion-method' => 'append' }, partial: 'spree/admin/invoice_lines/fields', class: 'button icon-plus' %>
        </fieldset>
        <div class="clear"></div>
      </div>
    </div>

    <div class="clear"></div>

    <%= render partial: 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>